### ISSUE TITLE
Change color or shape of original target-square.

### ISSUE THREAD

**Issue by vegiwoo** [maxxfrazer/FocusEntity#11]
**Describe the bug**
Can't change the color of the target square and the shape (if I don't really like the square)

**To Reproduce**
```
class CustomARView: ARView {
    var focusEntity: FocusEntity!

    required init (frame frameRect: CGRect) {
        super.init (frame: frameRect)

        focusEntity = FocusEntity (on: self, style: .classic (color: .red))
// оr focusEntity = FocusEntity (on: self, style: .colored (onColor: .white, offColor: .gray, otherColor: .blue, mesh: MeshResource.generateSphere (radius: 0.5)))
   
        focusEntity.delegate = self
        focusEntity.setAutoUpdate (to: true)
    }
    
    @objc required dynamic init? (coder decoder: NSCoder) {
        fatalError ("init (coder :) has not been implemented")
    }
}
```

**Expected behavior**
Change the color or shape of the original target square.

**Environment:**
 - iOS Version - 14.1
 - Device Information - iPhone XS Max
 - macOS Version - BigSur beta 11
 - Xcode Version - 12.0

**Comment by maxxfrazer** [comment]
Thanks for raising this @vegiwoo, found the issue and have started the fix (branch `color-fix`)

**Comment by maxxfrazer** [comment]
Release [v2.1.0](https://github.com/maxxfrazer/FocusEntity/releases/tag/v2.1.0) fixes the issue
