### ISSUE TITLE
Glitch in ARView

### ISSUE THREAD

**Issue by negarhaghbin** [maxxfrazer/FocusEntity#21]
**Describe the bug**
I  have an iOS application in which you can open an AR view by tapping on a button. However, after popping the view from my navigation controller and tapping on the AR button again something unusual happens in the camera feed. I see a sudden appearance of the last frame of my previous ar session that comes and goes during the whole session. 
Here is my code:
```
override func viewDidLoad() {
    super.viewDidLoad()
    focusSquare = FocusEntity(on: arview, style: .classic(color: .yellow))
    setupCoachingOverlay()
  }
   
  override func viewWillAppear(_ animated: Bool) {
    self.navigationController?.isNavigationBarHidden = true
  }
   
  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    UIApplication.shared.isIdleTimerDisabled = true
    resetTracking()
  }

  override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    arview.session.pause()
  }

  func resetTracking() {
    arview.automaticallyConfigureSession = false
    let configuration = ARWorldTrackingConfiguration()
    configuration.planeDetection = [.horizontal, .vertical]
    arview.session.run(configuration, options: [.resetTracking, .removeExistingAnchors])
    arview.scene.addAnchor(anchor)
  }
```

**To Reproduce**
1. Using the storyboard, create a view controller with a button and embed it in a navigation controller.
2. Create view controller number 2 which contains an ar view.
3. Tapping on the button in the view controller number 1 pushes the second view controller on the navigation controller.
3. Press back in the navigation bar from the second view controller (so that it's popped from the navigation controller)
4. Again tap on the button in the first view controller to open the second view controller.

**Expected behavior**
I expected to see the normal camera feed.

**Environment:**
 - iOS 14.4.2
 - iPhone 7
 - macOS Big Sur 11.2.2
 - Xcode 12.4

**Comment by negarhaghbin** [comment]
after reading the source code, I realized that I need to call `destroy()` for the focusSquare while deinitializing the second view controller.

**Comment by maxxfrazer** [comment]
@negarhaghbin the recent updates to FocusSquare from last month should fix this issue, are you still seeing it?

ARView can be quite funky when opening multiple of them in the same app session, even without FocusSquare

edit: by fixing the issue, you may not need to call destroy anymore, as the ARView reference is now weak

**Comment by negarhaghbin** [comment]
@maxxfrazer you're right. I was using version 2.2.1. In version 2.2.3 there's no need to call `destroy()`!
