### ISSUE TITLE
Issue when importing this Swift package to Swift Playgrounds 4 on iPad.

### ISSUE THREAD

**Issue by bobbygeo** [maxxfrazer/FocusEntity#31]
**Describe the bug**
I am using this project as part of a tutorial on the latest version of Swift Playgrounds 4 for the iPad. When trying to import the swift package nothing shows up in Swift Playgrounds to be able to import the project.

**To Reproduce**
1. Open Swift Playgrounds 4
2. Open an App project
3. Import Swift Package
4. Paste git url
5. Nothing happens

**Expected behavior**
The project version should appear when pasting the git url

**Screenshots**
[https://share.icloud.com/photos/0881xVKzop_6nPJCrTlZg7JDg](url)

**Environment:**
 - iPad OS 15.2
 - iPad Pro (11-inch) (3rd generation)
 - Swift Playgrounds 4

**Comment by maxxfrazer** [comment]
Hi Bobby, I'll checkout that error next week or at least early January - I haven't tested out Playgrounds 4 yet, but do have an iPad to test it out with at least. I'm guessing other packages imported from GitHub work without an issue?

**Comment by Schmitt-A** [comment]
Hi Max, thank you for the support. Yes other packages imported from GitHub working without any issue, but not all. I would say 8 / 10 are working. Thanks again :)

**Comment by maxxfrazer** [comment]
Found the issue - the tag was set to v2.2.4, which works fine on Xcode and in general on GitHub. But Swift Playgrounds on iPad only likes it if the tag is without the "v". I've just released "2.2.4" and it's showing up in Playgrounds for me now.

Please check it's okay for you too and we can close this issue.

**Comment by bobbygeo** [comment]
Hey Max, that’s awesome thank you for taking the time to update this! I confirm I am able to load the project too.
The other issue about base Color is still outstanding though. I have tried to modify the parameters but I am too early in the game to able to do it by myself.

**Comment by maxxfrazer** [comment]
perfect, i'll get to the base Colour stuff as soon as i can.

thanks again for flagging the swift playgrounds issue!
