### ISSUE TITLE
Transparent texture problem

### ISSUE THREAD

**Issue by Rus-Cosmin** [maxxfrazer/FocusEntity#34]
**Describe the bug**
The example with the png texture are not transparent

**To Reproduce**
1. Go to [example](https://github.com/maxxfrazer/FocusEntity/blob/main/FocusEntity-Example/FocusEntity-Example/FocusARView.swift#L33)
2. Try the material example
3. Try on a device
4. The png's are not transparent

**Expected behavior**
The texture is transparent

Problem seems to be [here](https://github.com/maxxfrazer/FocusEntity/blob/main/Sources/FocusEntity/FocusEntity%2BColored.swift#L34) 
Proposed fix
`modelMaterial.color = .init(tint: .white.withAlphaComponent(0.9999), texture: .init(tex))`

**Comment by maxxfrazer** [comment]
Oh damn, that's annoying - for some reason I thought this was fixed in iOS 15 🤦

Could you open a PR with the fix?

**Comment by Rus-Cosmin** [comment]
Yes, i will try:D first time making a PR
