### ISSUE TITLE
Closure containing control flow statement cannot be used with result builder 'ViewBuilder'

### ISSUE THREAD

**Issue by kharabe** [maxxfrazer/FocusEntity#43]
For this issue I created this correct solution 

import SwiftUI

struct ModelsByCategoryGridView: View {
    
    @Binding var showBrowse: Bool
    
    let models = Models()
    
    var body: some View {
        VStack {
            ForEach(ModelCategory.allCases, id: \.self) { category in
                // No need for optional binding here
                let modelsByCategory = models.get(category: category)
                
                // Check if the array is not empty before creating the HorizontalGridView
                if !modelsByCategory.isEmpty {
                    HorizontalGridView(showBrowse: $showBrowse, title: category.label, items: modelsByCategory)
                }
            }
        }
    }
}

**Comment by maxxfrazer** [comment]
sorry I'm not sure how this relates to FocusEntity?
